name: unit-tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    timeout-minutes: 10
    name: abap unit tests (transpiled)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Run transpiled unit tests
        run: sh bin/test.sh
